import { safeGetJson, safeSetJson, STORAGE_KEYS } from './storage';

export type EmojiGroupId = 'faces' | 'nature' | 'food' | 'activity' | 'objects' | 'symbols';

export interface EmojiEntry {
  emoji: string;
  keywords: string;
}

export interface EmojiGroup {
  id: EmojiGroupId;
  label: string;
  emojis: EmojiEntry[];
}

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    id: 'faces',
    label: 'Faces',
    emojis: [
      { emoji: '😀', keywords: 'grinning smile happy' },
      { emoji: '😄', keywords: 'smile happy joy' },
      { emoji: '😁', keywords: 'grin beaming' },
      { emoji: '😂', keywords: 'joy laugh tears' },
      { emoji: '🤣', keywords: 'rofl laugh rolling' },
      { emoji: '😊', keywords: 'blush shy happy' },
      { emoji: '😉', keywords: 'wink' },
      { emoji: '😍', keywords: 'heart eyes love' },
      { emoji: '🥰', keywords: 'smiling hearts love' },
      { emoji: '😘', keywords: 'kiss' },
      { emoji: '😋', keywords: 'yum tongue' },
      { emoji: '🤪', keywords: 'zany crazy' },
      { emoji: '🤔', keywords: 'thinking hmm consider' },
      { emoji: '🤨', keywords: 'skeptical eyebrow' },
      { emoji: '😐', keywords: 'neutral meh' },
      { emoji: '😑', keywords: 'expressionless' },
      { emoji: '🙄', keywords: 'eye roll' },
      { emoji: '😶', keywords: 'no mouth silent' },
      { emoji: '🫡', keywords: 'salute' },
      { emoji: '🤫', keywords: 'shush quiet' },
      { emoji: '🤭', keywords: 'oops giggle' },
      { emoji: '😴', keywords: 'sleeping sleepy' },
      { emoji: '😪', keywords: 'sleepy tired' },
      { emoji: '😷', keywords: 'mask sick' },
      { emoji: '🤒', keywords: 'sick fever' },
      { emoji: '🤕', keywords: 'hurt bandage' },
      { emoji: '🤢', keywords: 'nauseated' },
      { emoji: '🤯', keywords: 'mind blown explode' },
      { emoji: '🥳', keywords: 'party celebrate' },
      { emoji: '🤩', keywords: 'star struck' },
      { emoji: '😎', keywords: 'cool sunglasses' },
      { emoji: '🥸', keywords: 'disguise' },
      { emoji: '🤓', keywords: 'nerd geek' },
      { emoji: '😢', keywords: 'cry sad' },
      { emoji: '😭', keywords: 'sob cry loudly' },
      { emoji: '😤', keywords: 'triumph huff' },
      { emoji: '😡', keywords: 'angry rage mad' },
      { emoji: '🤬', keywords: 'swearing cursing' },
      { emoji: '😱', keywords: 'scream fear' },
      { emoji: '😨', keywords: 'fearful' },
      { emoji: '🥵', keywords: 'hot heat' },
      { emoji: '🥶', keywords: 'cold freezing' },
      { emoji: '🥴', keywords: 'woozy drunk' },
      { emoji: '😇', keywords: 'angel innocent' },
      { emoji: '🙃', keywords: 'upside down silly' },
      { emoji: '💀', keywords: 'skull dead' },
      { emoji: '👻', keywords: 'ghost' },
      { emoji: '👍', keywords: 'thumbs up like good' },
      { emoji: '👎', keywords: 'thumbs down dislike' },
      { emoji: '👏', keywords: 'clap applause' },
      { emoji: '🙌', keywords: 'raise hands celebrate' },
      { emoji: '🙏', keywords: 'pray thanks please' },
      { emoji: '💪', keywords: 'muscle strong flex' },
      { emoji: '👀', keywords: 'eyes look watch' },
      { emoji: '🤝', keywords: 'handshake deal' },
      { emoji: '✌️', keywords: 'victory peace' },
      { emoji: '👋', keywords: 'wave hello bye' },
      { emoji: '🤞', keywords: 'crossed fingers luck' },
      { emoji: '👌', keywords: 'ok okay' },
      { emoji: '🫶', keywords: 'heart hands love' },
      { emoji: '✍️', keywords: 'writing hand' },
      { emoji: '🧠', keywords: 'brain smart' },
      { emoji: '🦾', keywords: 'mechanical arm' },
      { emoji: '👤', keywords: 'person user profile' },
      { emoji: '👥', keywords: 'people team group' },
    ],
  },
  {
    id: 'nature',
    label: 'Nature',
    emojis: [
      { emoji: '🐶', keywords: 'dog puppy' },
      { emoji: '🐱', keywords: 'cat kitten' },
      { emoji: '🐭', keywords: 'mouse rat' },
      { emoji: '🐹', keywords: 'hamster' },
      { emoji: '🐰', keywords: 'rabbit bunny' },
      { emoji: '🦊', keywords: 'fox' },
      { emoji: '🐻', keywords: 'bear' },
      { emoji: '🐼', keywords: 'panda' },
      { emoji: '🐨', keywords: 'koala' },
      { emoji: '🐯', keywords: 'tiger' },
      { emoji: '🦁', keywords: 'lion' },
      { emoji: '🐮', keywords: 'cow' },
      { emoji: '🐷', keywords: 'pig' },
      { emoji: '🐸', keywords: 'frog' },
      { emoji: '🐵', keywords: 'monkey' },
      { emoji: '🐔', keywords: 'chicken' },
      { emoji: '🐧', keywords: 'penguin' },
      { emoji: '🐦', keywords: 'bird' },
      { emoji: '🐣', keywords: 'chick hatching' },
      { emoji: '🦆', keywords: 'duck' },
      { emoji: '🦉', keywords: 'owl' },
      { emoji: '🐝', keywords: 'bee' },
      { emoji: '🐛', keywords: 'bug caterpillar' },
      { emoji: '🦋', keywords: 'butterfly' },
      { emoji: '🐌', keywords: 'snail slow' },
      { emoji: '🐢', keywords: 'turtle slow' },
      { emoji: '🐍', keywords: 'snake' },
      { emoji: '🐙', keywords: 'octopus' },
      { emoji: '🦑', keywords: 'squid' },
      { emoji: '🦐', keywords: 'shrimp' },
      { emoji: '🦀', keywords: 'crab' },
      { emoji: '🐠', keywords: 'tropical fish' },
      { emoji: '🐳', keywords: 'whale' },
      { emoji: '🦈', keywords: 'shark' },
      { emoji: '🐊', keywords: 'crocodile' },
      { emoji: '🦄', keywords: 'unicorn' },
      { emoji: '🐴', keywords: 'horse' },
      { emoji: '🐑', keywords: 'sheep' },
      { emoji: '🐐', keywords: 'goat' },
      { emoji: '🦜', keywords: 'parrot' },
      { emoji: '🌸', keywords: 'blossom flower sakura' },
      { emoji: '🌹', keywords: 'rose flower' },
      { emoji: '🌻', keywords: 'sunflower' },
      { emoji: '🌷', keywords: 'tulip' },
      { emoji: '🌱', keywords: 'seedling sprout' },
      { emoji: '🌲', keywords: 'tree evergreen' },
      { emoji: '🌳', keywords: 'deciduous tree' },
      { emoji: '🌵', keywords: 'cactus' },
      { emoji: '🍀', keywords: 'clover luck' },
      { emoji: '🍁', keywords: 'maple leaf autumn' },
      { emoji: '🍄', keywords: 'mushroom' },
      { emoji: '🌈', keywords: 'rainbow' },
      { emoji: '☀️', keywords: 'sun sunny' },
      { emoji: '🌙', keywords: 'moon crescent' },
      { emoji: '⭐', keywords: 'star' },
      { emoji: '🌟', keywords: 'glowing star' },
      { emoji: '☁️', keywords: 'cloud' },
      { emoji: '⛅', keywords: 'partly cloudy' },
      { emoji: '🌧️', keywords: 'rain rainy' },
      { emoji: '❄️', keywords: 'snowflake snow' },
      { emoji: '⛄', keywords: 'snowman' },
      { emoji: '⚡', keywords: 'lightning bolt' },
      { emoji: '🔥', keywords: 'fire hot' },
      { emoji: '🌊', keywords: 'wave ocean sea' },
      { emoji: '🏔️', keywords: 'mountain snow' },
    ],
  },
  {
    id: 'food',
    label: 'Food',
    emojis: [
      { emoji: '☕', keywords: 'coffee' },
      { emoji: '🍵', keywords: 'tea' },
      { emoji: '🧋', keywords: 'bubble tea boba' },
      { emoji: '🥛', keywords: 'milk' },
      { emoji: '🍺', keywords: 'beer' },
      { emoji: '🍷', keywords: 'wine' },
      { emoji: '🥂', keywords: 'champagne cheers' },
      { emoji: '🥤', keywords: 'cup straw soda' },
      { emoji: '🧃', keywords: 'juice box' },
      { emoji: '🍎', keywords: 'apple' },
      { emoji: '🍊', keywords: 'orange tangerine' },
      { emoji: '🍋', keywords: 'lemon' },
      { emoji: '🍉', keywords: 'watermelon' },
      { emoji: '🍓', keywords: 'strawberry' },
      { emoji: '🍑', keywords: 'peach' },
      { emoji: '🥭', keywords: 'mango' },
      { emoji: '🍍', keywords: 'pineapple' },
      { emoji: '🥝', keywords: 'kiwi' },
      { emoji: '🍇', keywords: 'grapes' },
      { emoji: '🍒', keywords: 'cherries' },
      { emoji: '🥑', keywords: 'avocado' },
      { emoji: '🥦', keywords: 'broccoli' },
      { emoji: '🌽', keywords: 'corn' },
      { emoji: '🌶️', keywords: 'hot pepper spicy' },
      { emoji: '🍔', keywords: 'burger hamburger' },
      { emoji: '🍟', keywords: 'fries' },
      { emoji: '🍕', keywords: 'pizza' },
      { emoji: '🌭', keywords: 'hot dog' },
      { emoji: '🥪', keywords: 'sandwich' },
      { emoji: '🌮', keywords: 'taco' },
      { emoji: '🍜', keywords: 'ramen noodles' },
      { emoji: '🍝', keywords: 'spaghetti pasta' },
      { emoji: '🍣', keywords: 'sushi' },
      { emoji: '🍱', keywords: 'bento' },
      { emoji: '🥟', keywords: 'dumpling' },
      { emoji: '🍚', keywords: 'rice' },
      { emoji: '🍞', keywords: 'bread' },
      { emoji: '🥐', keywords: 'croissant' },
      { emoji: '🧀', keywords: 'cheese' },
      { emoji: '🍳', keywords: 'cooking egg' },
      { emoji: '🍦', keywords: 'ice cream' },
      { emoji: '🍰', keywords: 'cake' },
      { emoji: '🎂', keywords: 'birthday cake' },
      { emoji: '🍫', keywords: 'chocolate' },
      { emoji: '🍩', keywords: 'donut doughnut' },
      { emoji: '🍪', keywords: 'cookie' },
      { emoji: '🍭', keywords: 'lollipop' },
    ],
  },
  {
    id: 'activity',
    label: 'Activity',
    emojis: [
      { emoji: '⚽', keywords: 'soccer football' },
      { emoji: '🏀', keywords: 'basketball' },
      { emoji: '🏈', keywords: 'american football' },
      { emoji: '⚾', keywords: 'baseball' },
      { emoji: '🎾', keywords: 'tennis' },
      { emoji: '🏐', keywords: 'volleyball' },
      { emoji: '🏓', keywords: 'ping pong' },
      { emoji: '🏸', keywords: 'badminton' },
      { emoji: '🥊', keywords: 'boxing' },
      { emoji: '⛳', keywords: 'golf' },
      { emoji: '🎣', keywords: 'fishing' },
      { emoji: '🏊', keywords: 'swim' },
      { emoji: '🏄', keywords: 'surf' },
      { emoji: '🚴', keywords: 'cycling' },
      { emoji: '🏋️', keywords: 'weightlifting gym' },
      { emoji: '🧘', keywords: 'yoga meditation' },
      { emoji: '🎮', keywords: 'video game controller' },
      { emoji: '🎲', keywords: 'dice' },
      { emoji: '🎯', keywords: 'target bullseye' },
      { emoji: '🎳', keywords: 'bowling' },
      { emoji: '🎰', keywords: 'slot machine' },
      { emoji: '♟️', keywords: 'chess' },
      { emoji: '🎸', keywords: 'guitar' },
      { emoji: '🎹', keywords: 'piano keyboard' },
      { emoji: '🥁', keywords: 'drum' },
      { emoji: '🎤', keywords: 'microphone sing' },
      { emoji: '🎧', keywords: 'headphones' },
      { emoji: '🎬', keywords: 'clapper movie' },
      { emoji: '🎨', keywords: 'art palette paint' },
      { emoji: '🎭', keywords: 'theater masks' },
      { emoji: '🎪', keywords: 'circus' },
      { emoji: '🎡', keywords: 'ferris wheel' },
      { emoji: '✈️', keywords: 'airplane travel flight' },
      { emoji: '🚗', keywords: 'car drive' },
      { emoji: '🚕', keywords: 'taxi' },
      { emoji: '🚌', keywords: 'bus' },
      { emoji: '🚑', keywords: 'ambulance' },
      { emoji: '🚒', keywords: 'fire engine' },
      { emoji: '🚀', keywords: 'rocket launch ship' },
      { emoji: '🛸', keywords: 'ufo flying saucer' },
      { emoji: '🚲', keywords: 'bicycle bike' },
      { emoji: '🛴', keywords: 'scooter' },
      { emoji: '🚄', keywords: 'bullet train' },
      { emoji: '🚢', keywords: 'ship' },
      { emoji: '⛵', keywords: 'sailboat' },
      { emoji: '🏠', keywords: 'house home' },
      { emoji: '🏢', keywords: 'office building' },
      { emoji: '🏥', keywords: 'hospital' },
      { emoji: '🏫', keywords: 'school' },
      { emoji: '🏖️', keywords: 'beach vacation' },
      { emoji: '⛺', keywords: 'camping tent' },
      { emoji: '🌋', keywords: 'volcano' },
      { emoji: '🗺️', keywords: 'map world' },
      { emoji: '🧭', keywords: 'compass' },
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    emojis: [
      { emoji: '💻', keywords: 'laptop computer' },
      { emoji: '🖥️', keywords: 'desktop computer' },
      { emoji: '⌨️', keywords: 'keyboard' },
      { emoji: '🖱️', keywords: 'computer mouse' },
      { emoji: '📱', keywords: 'phone mobile' },
      { emoji: '🔋', keywords: 'battery' },
      { emoji: '🔌', keywords: 'plug electric' },
      { emoji: '💾', keywords: 'floppy save' },
      { emoji: '📀', keywords: 'cd disc' },
      { emoji: '🎥', keywords: 'movie camera' },
      { emoji: '📷', keywords: 'camera' },
      { emoji: '🔭', keywords: 'telescope' },
      { emoji: '📡', keywords: 'satellite antenna' },
      { emoji: '🌐', keywords: 'globe web internet' },
      { emoji: '🕯️', keywords: 'candle' },
      { emoji: '💡', keywords: 'bulb idea light' },
      { emoji: '🔦', keywords: 'flashlight' },
      { emoji: '📁', keywords: 'folder' },
      { emoji: '📂', keywords: 'open folder' },
      { emoji: '🗂️', keywords: 'card index archive' },
      { emoji: '📅', keywords: 'calendar date' },
      { emoji: '📌', keywords: 'pin pushpin' },
      { emoji: '📍', keywords: 'round pin location' },
      { emoji: '📎', keywords: 'paperclip attachment' },
      { emoji: '✂️', keywords: 'scissors cut' },
      { emoji: '📏', keywords: 'ruler' },
      { emoji: '📝', keywords: 'memo note write' },
      { emoji: '✏️', keywords: 'pencil edit write' },
      { emoji: '📄', keywords: 'document page' },
      { emoji: '📃', keywords: 'page curl' },
      { emoji: '📑', keywords: 'bookmark tabs' },
      { emoji: '📚', keywords: 'books' },
      { emoji: '📖', keywords: 'open book' },
      { emoji: '🔖', keywords: 'bookmark' },
      { emoji: '🏷️', keywords: 'label tag' },
      { emoji: '📊', keywords: 'bar chart stats' },
      { emoji: '📈', keywords: 'chart up growth' },
      { emoji: '📉', keywords: 'chart down' },
      { emoji: '🔍', keywords: 'search magnifier' },
      { emoji: '🔎', keywords: 'search magnifier right' },
      { emoji: '🔒', keywords: 'lock locked' },
      { emoji: '🔓', keywords: 'unlock open' },
      { emoji: '🔑', keywords: 'key' },
      { emoji: '🔧', keywords: 'wrench tool' },
      { emoji: '🔨', keywords: 'hammer' },
      { emoji: '🛠️', keywords: 'tools hammer wrench' },
      { emoji: '🧰', keywords: 'toolbox' },
      { emoji: '🪛', keywords: 'screwdriver' },
      { emoji: '🔩', keywords: 'nut and bolt screw' },
      { emoji: '🏗️', keywords: 'building construction crane' },
      { emoji: '⚙️', keywords: 'gear settings' },
      { emoji: '🧲', keywords: 'magnet' },
      { emoji: '⚗️', keywords: 'alembic' },
      { emoji: '🧪', keywords: 'test tube experiment' },
      { emoji: '🔬', keywords: 'microscope science' },
      { emoji: '🤖', keywords: 'robot bot' },
      { emoji: '👾', keywords: 'alien monster game' },
      { emoji: '💣', keywords: 'bomb' },
      { emoji: '🧨', keywords: 'firecracker' },
      { emoji: '🗑️', keywords: 'trash delete' },
      { emoji: '🧹', keywords: 'broom clean' },
      { emoji: '🧻', keywords: 'toilet paper' },
      { emoji: '🧽', keywords: 'sponge' },
      { emoji: '📦', keywords: 'package box' },
      { emoji: '✉️', keywords: 'envelope mail' },
      { emoji: '📮', keywords: 'mailbox postbox' },
      { emoji: '📧', keywords: 'email mail' },
      { emoji: '📥', keywords: 'inbox tray receive' },
      { emoji: '📤', keywords: 'outbox tray send' },
      { emoji: '📞', keywords: 'telephone receiver call phone' },
      { emoji: '💬', keywords: 'speech balloon chat message bubble' },
      { emoji: '💭', keywords: 'thought balloon thinking' },
      { emoji: '📣', keywords: 'megaphone announcement' },
      { emoji: '📢', keywords: 'loudspeaker broadcast' },
      { emoji: '🚨', keywords: 'police light alert emergency' },
      { emoji: '🗳️', keywords: 'ballot box vote' },
      { emoji: '🔗', keywords: 'link chain' },
      { emoji: '🧩', keywords: 'puzzle piece plugin' },
      { emoji: '🪄', keywords: 'magic wand' },
      { emoji: '🛡️', keywords: 'shield security' },
      { emoji: '⚔️', keywords: 'crossed swords' },
      { emoji: '💳', keywords: 'credit card' },
      { emoji: '💰', keywords: 'money bag' },
      { emoji: '🧾', keywords: 'receipt' },
      { emoji: '📿', keywords: 'prayer beads' },
      { emoji: '💍', keywords: 'ring' },
      { emoji: '👑', keywords: 'crown' },
      { emoji: '🎩', keywords: 'top hat' },
      { emoji: '🎒', keywords: 'backpack' },
      { emoji: '👓', keywords: 'glasses' },
      { emoji: '🌂', keywords: 'umbrella' },
      { emoji: '🕰️', keywords: 'mantel clock' },
      { emoji: '⌚', keywords: 'watch' },
      { emoji: '⏱️', keywords: 'stopwatch' },
      { emoji: '🧯', keywords: 'fire extinguisher' },
      { emoji: '🩹', keywords: 'bandage patch fix' },
      { emoji: '🎓', keywords: 'graduation cap study learn' },
      { emoji: '🎫', keywords: 'ticket' },
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    emojis: [
      { emoji: '✅', keywords: 'check done complete' },
      { emoji: '✔️', keywords: 'checkmark correct' },
      { emoji: '❌', keywords: 'cross x wrong' },
      { emoji: '❓', keywords: 'question help' },
      { emoji: '❔', keywords: 'white question' },
      { emoji: '❗', keywords: 'exclamation important' },
      { emoji: '❕', keywords: 'white exclamation' },
      { emoji: '⚠️', keywords: 'warning caution' },
      { emoji: '🚧', keywords: 'construction wip' },
      { emoji: '🚫', keywords: 'prohibited no' },
      { emoji: '💥', keywords: 'boom explosion' },
      { emoji: '✨', keywords: 'sparkles shiny' },
      { emoji: '🎉', keywords: 'tada party celebrate' },
      { emoji: '🎊', keywords: 'confetti party' },
      { emoji: '🏆', keywords: 'trophy champion' },
      { emoji: '🥇', keywords: 'gold medal first' },
      { emoji: '🥈', keywords: 'silver medal second' },
      { emoji: '🥉', keywords: 'bronze medal third' },
      { emoji: '🎖️', keywords: 'military medal' },
      { emoji: '🚩', keywords: 'red flag mark' },
      { emoji: '🏁', keywords: 'checkered flag finish' },
      { emoji: '⏳', keywords: 'hourglass time waiting' },
      { emoji: '⌛', keywords: 'hourglass done' },
      { emoji: '🕐', keywords: 'clock one time' },
      { emoji: '⏰', keywords: 'alarm clock' },
      { emoji: '🔔', keywords: 'bell notification' },
      { emoji: '🔕', keywords: 'bell slash mute' },
      { emoji: '🕹️', keywords: 'joystick game' },
      { emoji: '🔴', keywords: 'red circle record' },
      { emoji: '🟢', keywords: 'green circle online' },
      { emoji: '🟡', keywords: 'yellow circle' },
      { emoji: '🟠', keywords: 'orange circle' },
      { emoji: '🔵', keywords: 'blue circle' },
      { emoji: '🟣', keywords: 'purple circle' },
      { emoji: '⚫', keywords: 'black circle' },
      { emoji: '⚪', keywords: 'white circle' },
      { emoji: '🟥', keywords: 'red square' },
      { emoji: '🟩', keywords: 'green square' },
      { emoji: '🟦', keywords: 'blue square' },
      { emoji: '🔺', keywords: 'red triangle up' },
      { emoji: '🔻', keywords: 'triangle down' },
      { emoji: '🔸', keywords: 'diamond orange' },
      { emoji: '🔹', keywords: 'diamond blue' },
      { emoji: '💠', keywords: 'diamond dot' },
      { emoji: '🔶', keywords: 'diamond orange big' },
      { emoji: '🔷', keywords: 'diamond blue big' },
      { emoji: '▶️', keywords: 'play' },
      { emoji: '⏸️', keywords: 'pause' },
      { emoji: '⏹️', keywords: 'stop' },
      { emoji: '⏺️', keywords: 'record' },
      { emoji: '⏩', keywords: 'fast forward' },
      { emoji: '⏪', keywords: 'rewind' },
      { emoji: '🔀', keywords: 'shuffle' },
      { emoji: '🔁', keywords: 'repeat' },
      { emoji: '🔂', keywords: 'repeat one' },
      { emoji: '🔄', keywords: 'refresh sync' },
      { emoji: '🔃', keywords: 'reload' },
      { emoji: '➕', keywords: 'plus add' },
      { emoji: '➖', keywords: 'minus' },
      { emoji: '➗', keywords: 'divide' },
      { emoji: '✖️', keywords: 'multiply' },
      { emoji: '💲', keywords: 'dollar money' },
      { emoji: '™️', keywords: 'trademark' },
      { emoji: '©️', keywords: 'copyright' },
      { emoji: '®️', keywords: 'registered' },
      { emoji: '↔️', keywords: 'left right arrow' },
      { emoji: '⬆️', keywords: 'up arrow' },
      { emoji: '⬇️', keywords: 'down arrow' },
      { emoji: '➡️', keywords: 'right arrow' },
      { emoji: '⬅️', keywords: 'left arrow' },
      { emoji: '🔙', keywords: 'back' },
      { emoji: '🔜', keywords: 'soon' },
      { emoji: '🔝', keywords: 'top' },
      { emoji: '💤', keywords: 'zzz sleep' },
      { emoji: '🆕', keywords: 'new' },
      { emoji: '🆒', keywords: 'cool' },
      { emoji: '🆓', keywords: 'free' },
      { emoji: '🆗', keywords: 'ok' },
      { emoji: '🆙', keywords: 'up' },
      { emoji: '🆚', keywords: 'vs versus' },
      { emoji: '♾️', keywords: 'infinity' },
      { emoji: '💯', keywords: 'hundred perfect' },
      { emoji: '💢', keywords: 'anger' },
      { emoji: '♨️', keywords: 'hot springs' },
      { emoji: '🚸', keywords: 'children crossing' },
      { emoji: '🔞', keywords: 'no one under eighteen' },
      { emoji: '📵', keywords: 'no mobile phones' },
      { emoji: '❤️', keywords: 'red heart love' },
      { emoji: '🧡', keywords: 'orange heart' },
      { emoji: '💛', keywords: 'yellow heart' },
      { emoji: '💚', keywords: 'green heart' },
      { emoji: '💙', keywords: 'blue heart' },
      { emoji: '💜', keywords: 'purple heart' },
      { emoji: '🖤', keywords: 'black heart' },
      { emoji: '🤍', keywords: 'white heart' },
      { emoji: '🤎', keywords: 'brown heart' },
      { emoji: '💔', keywords: 'broken heart' },
      { emoji: '💕', keywords: 'two hearts' },
      { emoji: '💖', keywords: 'sparkling heart' },
      { emoji: '💗', keywords: 'growing heart' },
    ],
  },
];

const ALL_EMOJIS = EMOJI_GROUPS.flatMap((group) => group.emojis);
const emojiPresentation = /\p{Emoji_Presentation}/u;
const regionalIndicator = /\p{Regional_Indicator}/u;
const extendedPictographic = /\p{Extended_Pictographic}/u;
const variationSelector16 = '\uFE0F';
let segmenter: Intl.Segmenter | undefined;

function firstGrapheme(value: string): { segment: string; index: number } | undefined {
  if (typeof Intl.Segmenter === 'function') {
    segmenter ??= new Intl.Segmenter('und', { granularity: 'grapheme' });
    return segmenter.segment(value)[Symbol.iterator]().next().value;
  }
  const points = Array.from(value);
  if (points.length === 0) return undefined;
  const first = points[0] ?? '';
  const second = points[1] ?? '';
  if (regionalIndicator.test(first) && regionalIndicator.test(second)) {
    return { segment: first + second, index: 0 };
  }
  return { segment: first + (second === variationSelector16 ? second : ''), index: 0 };
}

export function isEmojiGrapheme(value: string): boolean {
  return emojiPresentation.test(value) || regionalIndicator.test(value) ||
    (extendedPictographic.test(value) && value.includes(variationSelector16));
}

export function splitTitleEmoji(title: string): { emoji: string | null; rest: string } {
  const first = firstGrapheme(title);
  if (first === undefined || !isEmojiGrapheme(first.segment)) return { emoji: null, rest: title };
  return {
    emoji: first.segment,
    rest: title.slice(first.index + first.segment.length).replace(/^\s+/, ''),
  };
}

export function composeTitle(emoji: string | null, rest: string): string {
  const title = splitTitleEmoji(rest).rest.trim();
  const prefix = emoji?.trim() ?? '';
  return prefix ? (title ? `${prefix} ${title}` : prefix) : title;
}

export function searchEmoji(query: string, limit = 24): string[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return [];
  const matches: string[] = [];
  for (const entry of ALL_EMOJIS) {
    if ((entry.keywords.includes(normalized) || entry.emoji === normalized) &&
        matches.push(entry.emoji) >= limit) break;
  }
  return matches;
}

export const RECENT_EMOJI_LIMIT = 24;

export function loadRecentEmojis(): string[] {
  const value = safeGetJson<unknown>(STORAGE_KEYS.recentEmojis);
  if (!Array.isArray(value)) return [];
  return value.filter((emoji): emoji is string => typeof emoji === 'string').slice(0, RECENT_EMOJI_LIMIT);
}

export function recordRecentEmoji(emoji: string): string[] {
  const next = [emoji, ...loadRecentEmojis().filter((value) => value !== emoji)].slice(0, RECENT_EMOJI_LIMIT);
  safeSetJson(STORAGE_KEYS.recentEmojis, next);
  return next;
}
