import type { ModelCostRates } from './capability';

/**
 * Token usage breakdown for a single LLM generation.
 *
 * Providers map their native usage counters into this common shape so
 * callers can aggregate costs without caring about the backend.
 */
export interface TokenUsage {
  /** Input tokens that were neither cache-read nor cache-created. */
  inputOther: number;
  /** Output (completion) tokens generated by the model. */
  output: number;
  /** Input tokens served from the provider's prompt cache. */
  inputCacheRead: number;
  /** Input tokens written into the provider's prompt cache. */
  inputCacheCreation: number;
}

/**
 * Compute total input tokens (other + cache read + cache creation).
 */
export function inputTotal(usage: TokenUsage): number {
  return usage.inputOther + usage.inputCacheRead + usage.inputCacheCreation;
}

/**
 * Compute grand total tokens (input total + output).
 */
export function grandTotal(usage: TokenUsage): number {
  return inputTotal(usage) + usage.output;
}

/**
 * Create a zero-valued TokenUsage.
 */
export function emptyUsage(): TokenUsage {
  return {
    inputOther: 0,
    output: 0,
    inputCacheRead: 0,
    inputCacheCreation: 0,
  };
}

/**
 * Sum two TokenUsage values.
 */
export function addUsage(a: TokenUsage, b: TokenUsage): TokenUsage {
  return {
    inputOther: a.inputOther + b.inputOther,
    output: a.output + b.output,
    inputCacheRead: a.inputCacheRead + b.inputCacheRead,
    inputCacheCreation: a.inputCacheCreation + b.inputCacheCreation,
  };
}

/** Compute the USD cost of token usage from per-million-token rates. */
export function calculateCost(
  usage: TokenUsage,
  rates?: ModelCostRates,
): number | undefined {
  if (rates === undefined || !Object.values(rates).some(isValidRate)) return undefined;

  const charges = [
    charge(usage.inputOther, rates.input),
    charge(usage.output, rates.output),
    charge(usage.inputCacheRead, rates.cacheRead),
    charge(usage.inputCacheCreation, rates.cacheWrite),
  ];
  let total = 0;
  for (const cost of charges) {
    if (cost === undefined) return undefined;
    total += cost;
  }
  return total;
}

function charge(tokens: number, rate: number | undefined): number | undefined {
  if (tokens === 0) return 0;
  return isValidRate(rate) ? (tokens * rate) / 1_000_000 : undefined;
}

function isValidRate(rate: unknown): rate is number {
  return typeof rate === 'number' && Number.isFinite(rate) && rate >= 0;
}
